var width = 100;
var height = 50;
var area = width * height;
console.log('value of area: ', area);
console.log('typeof area: ', area);
var bill = 59;
var payment = 100;
var change = payment - bill;
console.log('value of change: ', change);
console.log('typeof change: ', typeof (change));
var quizzes = 60;
var midterm = 99;
var final = 80;
var grade = (quizzes + midterm + final) / 3;
console.log('value of grade: ', grade);
console.log('typeof grade: ', typeof (grade));
var firstName = 'Sean';
var lastName = 'Hughes';
var fullName = firstName + ' ' + lastName;
console.log('value of fullName: ', fullName);
console.log('typeof fullName: ', typeof (fullName));
var ph = 33;
var isAcidic = ph < 7;
console.log('value of isAcidic: ', isAcidic);
console.log('typeof isAcidic: ', typeof (isAcidic));
var headCount = 250;
var isSparta = headCount === 300;
console.log('value of isSparta: ', isSparta);
console.log('typeof isSparta: ', typeof (isSparta));
var motto = fullName;
motto = fullName + ' is the GOAT';
console.log('value of motto: ', motto);
console.log('typeof motto: ', typeof (motto));
